### register
POST http://localhost:3000/api/users/register

{
    "username": "wahyu",
    "email": "wahyuhjr@gmail.com",
    "password": "wahyu123"
}

### login
POST http://localhost:3000/api/users/login/

{
    "email": "admin@gmail.com",
    "password": "admin"
}

### get all users
GET http://localhost:3000/api/users/

### create ticket
POST http://localhost:3000/api/tickets/

{
    "title": "ticket 1",
    "description": "description 1",
    "userId": "2860579e-e315-42b5-a6ad-3fd4b16bae9d"
}